name: FxCop Analysis
on:
  pull_request:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install Dependencies
        run: dotnet restore

      - name: Run FxCop Analyzer
        run: dotnet build --no-restore /p:EnableNETAnalyzers=true

      - name: Report Analysis Results
        run: echo "FxCop analysis completed."
